spring.config.import=optional:classpath:shared.properties,optional:classpath:shared-dev.properties
spring.application.name=configurator
server.port=28081
springdoc.swagger-ui.enabled=false
springdoc.api-docs.path=/internal/docs/api-docs
