# === Banco de dados ===
spring.datasource.url=jdbc:postgresql://localhost:5432/finlumia_transactions
spring.datasource.username=postgres
spring.datasource.password=123456

# === Pool de conexões (HikariCP — já vem com o Spring JDBC) ===
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000