spring.config.import=optional:classpath:shared.properties,optional:classpath:shared-${spring.profiles.active:local}.properties
spring.application.name=document
server.port=28085
springdoc.swagger-ui.enabled=false
springdoc.api-docs.path=/internal/docs/api-docs
