spring.config.import=optional:classpath:shared.properties,optional:classpath:shared-dev.properties
spring.application.name=identify
server.port=28083
springdoc.swagger-ui.enabled=false
springdoc.api-docs.path=/internal/docs/api-docs

finlumia.identify.jwt.issuer=finlumia-identify
finlumia.identify.jwt.secret=${JWT_SECRET}
finlumia.identify.jwt.access-token-expiration-seconds=900
finlumia.identify.jwt.refresh-token-expiration-seconds=2592000

finlumia.identify.security.public-api.paths[0]=/api/identify/token
finlumia.identify.security.public-api.paths[1]=/api/identify/token/**
finlumia.identify.security.public-api.paths[2]=/api/identify/auth/login/google
finlumia.identify.security.public-api.paths[3]=/api/identify/auth/forgot-password
finlumia.identify.security.public-api.paths[4]=/api/identify/auth/verify-reset-token
finlumia.identify.security.public-api.paths[5]=/api/identify/auth/reset-password
finlumia.identify.security.public-api.paths[6]=/api/identify/auth/register
finlumia.identify.security.public-api.paths[7]=/api/identify/auth/verify-email
finlumia.identify.security.public-api.paths[8]=/api/identify/auth/resend-verification
